#!/bin/bash

## directory path
base_dir=$(cd $(dirname $0);pwd)
backup_dir=$base_dir/backup/`date +%Y%m%d_%k%M%S`

## make backup dir
mkdir $backup_dir

## deploy dotfiles
find $base_dir -maxdepth 1 -type f -name ".*" | while read f; do
  dotfile=$(basename $f)

  # backup original files if exists
  if [ -f ~/$dotfile ] ; then
    cp ~/$dotfile $backup_dir/
  fi

  cp $base_dir/$dotfile ~/
done
