#!/bin/bash

## directory path
base_dir=$(cd $(dirname $0);pwd)
backup_dir=$base_dir/backup/`date +%Y%m%d_%H%M%S`

## deploy dotfiles
files=`find $base_dir -maxdepth 1 -type f -name ".*"`
for f in $files; do
  dotfile=$(basename $f)

  # backup original files if exists
  if [ -f ~/$dotfile ] ; then
    mkdir -p $backup_dir
    cp ~/$dotfile $backup_dir/
  fi

  cp -i $base_dir/$dotfile ~/
done
